name: Deploy Web to Cloudflare Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - 'preprocessor/**'
      - 'pdf-render/**'
      - 'live-data-fetcher/**'
  workflow_dispatch:

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build staging web
        run: cd web && yarn build && cd ..
        env:
          BUILD_TARGET: staging
          PUBLIC_FIREBASE_CONFIG: ${{ secrets.PUBLIC_FIREBASE_CONFIG }}
          PUBLIC_FIREBASE_ADMIN: ${{ secrets.PUBLIC_FIREBASE_ADMIN }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: amnesty-people
          directory: ./web/dist
          branch: staging
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build production web
        run: cd web && yarn build && cd ..
        env:
          BUILD_TARGET: production
          PUBLIC_FIREBASE_CONFIG: ${{ secrets.PUBLIC_FIREBASE_CONFIG }}
          PUBLIC_FIREBASE_ADMIN: ${{ secrets.PUBLIC_FIREBASE_ADMIN }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: amnesty-people
          directory: ./web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
